### ISSUE TITLE
not running with react-native 0.28 [ios, android]

### ISSUE THREAD

**Issue by fabriziomoscon** [jlyman/RN-NavigationExperimental-Redux-Example#21]
This repo looks promising for learning and understanding how to use NavigationExperimental, the code is clean and easy to follow, but when I tried to run it doesn't work.

error on ios:

<img width="373" alt="screen shot 2016-06-24 at 11 41 33" src="https://cloud.githubusercontent.com/assets/721890/16335873/fbd90df0-3a00-11e6-8ebd-02e0470a80d4.png">

I tried also to run `react-native upgrade` but the result it the same.

It might require some changes after the release of `0.28`

error on android:

![screenshot_2016-06-24-12-15-00](https://cloud.githubusercontent.com/assets/721890/16336494/ff01f9a6-3a05-11e6-999c-47f766d7364a.png)

**Comment by jlyman** [comment]
The recent versions have introduced a lot of breaking changes to NavExp, and I just haven't had a chance to keep up with them. I'll revisit v0.28 today and try to bring it up to speed.

**Comment by jlyman** [comment]
Check the most recent push, it's looking mostly good. I think the issue was that I had switched the master branch to follow the `react-native/master` and forgot to switch it back to 0.27. Switching it to follow now 0.28 is just fine. Let me know if you see otherwise (there is still a known bug on popping from the third to home screens, working on that).

**Comment by fabriziomoscon** [comment]
Thanks! Super fast.
Now on both android and ios the app runs.

Unrelated, there is a minor problem on Third Screen when tapping on `Go to Home Page`

<img width="373" alt="screen shot 2016-06-24 at 16 41 30" src="https://cloud.githubusercontent.com/assets/721890/16342566/be703220-3a2a-11e6-9beb-8e651c52b2b6.png">

**Comment by jlyman** [comment]
Awesome, glad it worked! And yes, that issue is what I was referring to with the known bug I mentioned at the end. Still have to work on that.

On Fri, Jun 24, 2016 at 9:47 AM, Fabrizio Moscon notifications@github.com wrote:
Thanks! Super fast.
Now on both android and ios the app runs.

Unrelated, there is a minor problem on Third Screen when tapping on Go to Home Page

[https://cloud.githubusercontent.com/assets/721890/16342566/be703220-3a2a-11e6-9beb-8e651c52b2b6.png]
