### ISSUE TITLE
Having trouble with the NAV_RESET actionType

### ISSUE THREAD

**Issue by msageryd** [jlyman/RN-NavigationExperimental-Redux-Example#23]
I can't get the NAV_RESET actionType to work in the example. I'm using RN 0.28.

When I try to reset to Home screen from "Third" I get "No active scene found". There seems to be some kind of trouble in renderOverlay. Is this a problem with the example or is it in NavigationExperimental? 

I'm sorry if the answer is obvious. I'm completely new to this and I have spent a couple of days trying to wrap my head around react-native, redux and navigationExperimental. 

I tried to upgrade to react-native 0.29rc2, but then nothing works. I suppose there are breaking changes, but I can't find any information about it. It maybe gets clearer in a couple of hours when 0.29 is released.

**Comment by wsun** [comment]
`_renderOverlay` in NavigationTransitioner looks for the active scene by examining whether the scene route equals the current state route (https://github.com/facebook/react-native/blob/0.28-stable/Libraries/NavigationExperimental/NavigationTransitioner.js#L226).

The problem is that `NAV_RESET` has replaced state with a new route object, so it is no longer identical and thus `_renderOverlay` can't find an appropriate active scene. 

(`NavigationScenesReducer`, which generates the scenes, [reuses scenes](https://github.com/facebook/react-native/blob/0.28-stable/Libraries/NavigationExperimental/Reducer/NavigationScenesReducer.js#L159) if they're shallow equal. In this case, the previous route for the first page is being used, hence the inequality between the route in `navigationState` and the route in the scene.)

There is a fix which addresses this issue, but unfortunately I don't believe it's in 0.29rc:
https://github.com/facebook/react-native/commit/229d6d2fd0eb1efdd5257303e2c25493730e0450

**Comment by msageryd** [comment]
Thank you so much for the information. Now I can stop wondering if I have made something wrong. I'll wait with the reset until it's fixed.
