### ISSUE TITLE
Changing Title from component

### ISSUE THREAD

**Issue by lucadegasperi** [jlyman/RN-NavigationExperimental-Redux-Example#5]
Hello and thanks for this awesome example, it's the first one I've actually managed to get working. 
I've got a question: In your example, the title of the next view is passed down by calling the action with a parameter. What if I would like to set the title in the navigation bar from the component being rendered itself?

**Comment by jlyman** [comment]
Glad it's been helpful! I'm still learning about it as well.

In the example the fact that the title comes from the action.key is simply a convenience. In reality, the state that is passed to the `navigatePush()` action creator and on to the reducer can contain more than just a key identifying the scene. **It is key to know that the children objects in the nav state must have a key, but can also contain any other metadata, like titles.**

For example, it can contain the whole state object, which might look like `navigatePush({ key: 'NewScreen', title: 'My Title Here' })`, and the `NavigationHeader` in `AppContainer.js` can be changed to look for the title property of the scene object instead of key. 

In regards to having the title come from somewhere else though, I wouldn't necessarily recommend it come from the rendered component, because the rendered component should remain dumb and rely only on existing state. Instead, it should be determined somewhere upstream, probably in a reducer or passed in to an action creator like I talked about earlier. For example, I've got this action creator in an app I'm working on (simplified):

```
export function openThing(id, title, status) {
    return (dispatch) => {
        dispatch(startThing(id))

        if (status === 'complete') {
            dispatch(navigatePush({ key: 'Summary', title: 'Thing Summary' }))
        } else {
            dispatch(navigatePush({ key: 'Thing', title: title }))
        }
    }
}
```

The title in the nav bar will change depending on what "thing" is selected by the user and passed in to the action creator. Depending on how you write your reducers, this could be determined there as well.

**Comment by lucadegasperi** [comment]
To you does it make sense to have a reducer that manages the state of the navigation bar and where a container or component can update that navigation state by calling some action creators? I'm thinking about a list that has a viewing and an editing mode. That would not change the navigation stack but will update the title and buttons to allow the user to act accordingly

**Comment by jlyman** [comment]
I would think that having such a "mode" indicator in the application state would make sense, yes. It probably wouldn't be buried in or related explicitly to the properties of the navigation bar in the state, but it would probably have some sort of property on the main state that is `mode: 'editing' | 'viewing'` that gets flipped when appropriate actions trigger it, and that are used to build the string for the title of the nav bar.

**Comment by jlyman** [comment]
Going to close this, but if anyone else has thoughts/questions on this feel free to comment.
