### ISSUE TITLE
left and right buttons in `NavigationHeader`

### ISSUE THREAD

**Issue by yonahforst** [jlyman/RN-NavigationExperimental-Redux-Example#9]
Is there a recommended way to add buttons to the navigation header? I'm able to hack it by extending `NavigationHeader` but it feels really hacky:

``` js
export default class MyNavigationHeader extends NavigationHeader {
  _renderRightButton(): ?ReactElement {
    if (typeof this.props.onRightPress !== 'function') {
      return null;
    }
    return (
      <TouchableOpacity style={styles.rightButton} onPress={this.props.onRightPress}>
        <Image resizeMode='contain' source={require('../assets/menu-alt-64.png')} style={styles.rightButtonImage} />
      </TouchableOpacity>
    );
  }
  render() {
    return (
        <View style={styles.header}>
            {super.render()}
            {this._renderRightButton()}
        </View>
        )
  }
}
```

**Comment by jlyman** [comment]
You're on the right track, because `NavigationHeader` provides the `renderRightComponent` prop that essentially does what you are doing here. You can pass that button in directly to that prop on the original nav header and that should be good.

Note that [I'm overriding one of the other built-in nav header props (`renderTitleComponent`) in the example](https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/blob/master/app/containers/AppContainer.js#L35) to put in a more flexible title control.

**Comment by yonahforst** [comment]
Oh that's cool! I was looking for a props like that but couldn't find it. Probably because I'm on rn 0.22.2.

I'll try upgrading. thanks!

**Comment by jlyman** [comment]
Ah gotchya. Yep, things are moving quickly. :)

**Comment by yonahforst** [comment]
done! it's worked a charm. Thanks again.

``` js
          <NavigationHeader
            {...props}
            renderTitleComponent={props => {
              const title = props.scene.navigationState.title
              return <NavigationHeader.Title>{title}</NavigationHeader.Title>
            }}
            renderRightComponent={props => {
              return <TouchableHighlight style={styles.rightButton} onPress={()=> this._drawer.open()}>
                      <Image style={styles.rightIcon} resizeMode='contain' source={require('../assets/menu-alt-64.png')}/>
                     </TouchableHighlight>
            }}
          />
```
